### ISSUE TITLE
_.toPath replacement will fail on paths like `a["b]c"]`

### ISSUE THREAD

**Issue by jedwards1211** [cedmax/youmightnotneed#166]
This will harm less knowledgable users who copy this example:

```js
const toPath = path => path.match(/([^[.\]])+/g)
> toPath('a["b]c"]')
['a', '"b', 'c"']
```
Correct behavior:
```js
_.toPath('a["b]c"]')
(2) ['a', 'b]c']
```

**Comment by cedmax** [comment]
@jedwards1211 I appreciate your point, but this repo is not meant to be a drop in replacement for lodash: it's more of an educational opportunity to understand how to achieve similar results. To me this feels very much and edge case (as in, it's not extremely common to have object keys with square brackets in it). I wouldn't be against a PR fixing the Regex if anyone wanted to propose a change, though

**Comment by jedwards1211** [comment]
There's a lot of people out there who copy and paste code carelessly so to me there should at least be a warning because this just invites those people to do more damage.

Object keys with dots in them are probably more common than square brackets.

**Comment by cedmax** [comment]
There is a disclaimer 😅

<img width="815" alt="Screenshot 2021-12-30 at 16 06 35" src="https://user-images.githubusercontent.com/415593/147763494-d51d2879-3e4d-4b09-a300-16bdc80a02a3.png">

Feature parity was never the goal of this project and whilst you are right, there is people that will copy/paste a-critically, it's unfeasible to rewrite Lodash bottom up to solve that problem. 

Let me think if I can do something like intercepting the copy command and show a warning, instead of trying to play whack-a-mole with all the possible edge cases that might creep up. Do you think this approach could work?

**Comment by cedmax** [comment]
@jedwards1211 as per the [PR just merged](https://github.com/cedmax/youmightnotneed/pull/168), now when copy/pasting from any vanilla code blocks, the users will get an extra couple of commented lines in their clipboard:

```js
// WARNING: This is not a drop in replacement solution and
// it might not work for some edge cases. Test your code! 
const toPath = path => path.match(/([^[.\]])+/g)
```

I appreciate it's not a fix for the issue you raised initially, but I hope it helps mitigating the risk of people assuming that it will work exactly as Lodash.

**Comment by jedwards1211** [comment]
Yeah that's a good idea.  A lot of lodash functions are pretty simple to reimplement with the same behavior (at least for an array- or object-only usage) so this one stood out to me because the full underlying behavior is pretty complicated.
