### ISSUE TITLE
lodash remove function has waste

### ISSUE THREAD

**Issue by SgtPooki** [cedmax/youmightnotneed#167]
Result is set on line 5, not touched, and then returned. Lines 4 & 9 should be removed.

https://github.com/cedmax/youmightnotneed/blame/production/src/content/lodash/array/remove/vanilla.js#L5-L9

**Comment by cedmax** [comment]
I disagree: `_.remove` mutates the original array, so you can't just filter from it (that's what `_.filter` does). Since we are mutating the original array, we also need to be mindful not to do it before we run the original list of items against the iteratee condition, otherwise that could lead to weird results (the second example, for instance, `remove(newArray, () => newArray.length > 0)` wouldn't work if we mutate it as we go). I will close the issue for now, but please feel free to reopen it if I misunderstood

**Comment by cedmax** [comment]
as a reference to what I meant: https://github.com/cedmax/youmightnotneed/issues/98
