### ISSUE TITLE
Property based tests

### ISSUE THREAD

**Issue by 102** [cedmax/youmightnotneed#73]
It looks like this project is a good example of things that can have property-based testing (that can be implemented with the help of, for example, [fast-check](https://github.com/dubzzz/fast-check)).

Basically, this type of tests will allow us to write assertions that will look something like 

For any `X` that is string and any `Y` that is natural number, `X.repeat(Y) === _.repeat(X, Y)`

**Comment by cedmax** [comment]
I wasn't familiar with fast-check or property based testing, but I see how it could be handy for youmightnotneed.
 
But by looking at the docs, I have a concern: wouldn't we make codebase a little less "obvious"? Given the divulgative nature of the project, I'd rather keep it readable/understandable by most developers, no matter their level of expertise.

I might be overthinking this, though.

**Comment by 102** [comment]
We can keep them separate (as some kind of e2e tests) leaving the current layout of the content as is

**Comment by cedmax** [comment]
I'm closing this because as much as I appreciate the idea, I don't think it would add much to the project at this point, while it might introduce a steeper curve for people to be able to contribute (and on top of that to be completely honest I don't really have enough time to jump on learning it myself 😅 )
